# pyproject.toml
[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "DocsRay"
version = "0.1.0"
description = "PDF Question-Answering System with MCP Integration"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Taehoon Kim", email = "taehoonkim@sogang.ac.kr"},
]
keywords = ["pdf", "rag", "mcp", "llm", "embedding"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/MIMICLab/DocsRay"
Documentation = "https://github.com/MIMICLab/DocsRay/blob/main/README.md"
Repository = "https://github.com/MIMICLab/DocsRay"
Issues = "https://github.com/MIMICLab/DocsRay/issues"

[tool.setuptools.packages.find]
include = ["docsray*"]
exclude = ["tests*"]