# .github/workflows/publish.yml
name: Upload DocsRay to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Manual execution allowed

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    name: Build DocsRay Package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Prepare build environment
        run: |
          # Clean existing build files
          rm -rf dist/ build/ *.egg-info/
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Build release distributions
        run: |
          echo "Building DocsRay package..."
          python -m build
          echo "Build completed"

      - name: Verify build
        run: |
          echo "Verifying build results..."
          ls -la dist/
          python -m twine check dist/*

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: docsray-release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    name: Publish to PyPI
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
      url: https://pypi.org/project/docsray

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: docsray-release-dists
          path: dist/

      - name: Verify distributions before upload
        run: |
          echo "📋 List of Files to Upload:"
          ls -la dist/
          echo "📊 Number of Files: $(ls dist/ | wc -l)"

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          print: true  

  post-release:
    runs-on: ubuntu-latest
    needs: pypi-publish
    name: Post-release tasks
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create post-release summary
        run: |
          echo "🎉 DocsRay release completed!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📦 **Package Information:**" >> $GITHUB_STEP_SUMMARY
          echo "- Name: docsray" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- PyPI: https://pypi.org/project/docsray" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🚀 **Installation:**" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "pip install docsray" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📚 **Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "1. Test package installation" >> $GITHUB_STEP_SUMMARY
          echo "2. Update documentation" >> $GITHUB_STEP_SUMMARY
          echo "3. Notify users" >> $GITHUB_STEP_SUMMARY
